import os, re

ws_dir = r"C:\Users\Administrator\Documents\Kimi\Workspaces\mgfsk_viterbi"

replacements = [
    ("每符号采样数 = 16", "Samples per symbol = 16"),
    ("4进制", "4-ary"),
    ("调制指数：相邻tone间隔 = h*Rs = 1000 Hz", "Modulation index: adjacent tone spacing = h*Rs = 1000 Hz"),
    ("调制指数：", "Modulation index: "),
    ("相邻tone间隔", "Adjacent tone spacing"),
    ("高斯滤波BT", "Gaussian filter BT"),
    ("高斯滤波span", "Gaussian filter span"),
    ("符号数", "Symbol count"),
    ("有效符号数", "Valid symbol count"),
    ("非线性EbN0分布：0~12dB", "Nonlinear EbN0 distribution: 0~12dB"),
    ("非线性EbN0分布", "Nonlinear EbN0 distribution"),
    ("每点仿真次数", "Simulations per point"),
    ("接收前端", "Receiver frontend"),
    ("接收后端", "Receiver backend"),
    ("辅助函数：", "Helper function: "),
    ("辅助函数", "Helper function"),
    ("生成GFSK信号", "Generate GFSK signal"),
    ("预计算：", "Precompute: "),
    ("验证参考模板", "Verify reference templates"),
    ("参考模板", "Reference template"),
    ("测量", "Measure"),
    ("Viterbi 解码器", "Viterbi decoder"),
    ("Viterbi 序列检测", "Viterbi sequence detection"),
    ("ISI 感知 Viterbi", "ISI-aware Viterbi"),
    ("硬判决（逐符号最大模）", "Hard decision (per-symbol max magnitude)"),
    ("硬判决", "Hard decision"),
    ("软判决", "Soft decision"),
    ("分支度量", "Branch metric"),
    ("前向递推", "Forward recursion"),
    ("回溯", "Traceback"),
    ("全帧回溯", "Full-frame traceback"),
    ("归一化防溢出", "Normalization prevents overflow"),
    ("无噪声 Viterbi 自检", "Noiseless Viterbi self-check"),
    ("无噪声", "Noiseless"),
    ("自检", "Self-check"),
    ("状态定义", "State definition"),
    ("状态数", "Number of states"),
    ("状态转移", "State transition"),
    ("路径度量", "Path metric"),
    ("累计路径度量", "Cumulative path metric"),
    ("幸存路径", "Survivor path"),
    ("最优路径", "Optimal path"),
    ("主仿真：", "Main simulation: "),
    ("主仿真", "Main simulation"),
    ("Eb/N0 扫描", "Eb/N0 sweep"),
    ("AWGN 噪声", "AWGN noise"),
    ("AWGN + 信道滤波", "AWGN + channel filter"),
    ("噪声方差计算", "Noise variance calculation"),
    ("功率校验", "Power check"),
    ("蒙特卡洛", "Monte Carlo"),
    ("仿真结果", "Simulation results"),
    ("仿真时间", "Simulation time"),
    ("运行仿真", "Run simulation"),
    ("可调参数", "Adjustable parameters"),
    ("使用说明", "Usage instructions"),
    ("可视化", "Visualization"),
    ("信号频谱", "Signal spectrum"),
    ("星座图", "Constellation diagram"),
    ("误码率曲线", "BER curve"),
    ("错误位置", "Error locations"),
    ("对比", "Comparison"),
    ("增益", "Gain"),
    ("分析", "Analysis"),
    ("统计", "Statistics"),
    ("扫描", "Scan"),
    ("优化", "Optimize"),
    ("测试", "Test"),
    ("评估", "Evaluate"),
    ("性能", "Performance"),
    ("指标", "Metrics"),
    ("结果", "Results"),
    ("结果汇总", "Result summary"),
    ("结论", "Conclusion"),
    ("验证", "Verification"),
    ("确认", "Confirm"),
    ("检查", "Check"),
    ("符号内部分支度量", "Intra-symbol branch metrics"),
    ("Tone LPF 阶数测试", "Tone LPF order test"),
    ("8-GFSK 符号内 tone 度量分析", "8-GFSK intra-symbol tone metrics analysis"),
    ("4-Branch Tone-Mixer 逐符号测量", "4-Branch Tone-Mixer per-symbol measurement"),
    ("每分支最优相位", "Per-branch optimal phase"),
    ("采样相位扫描", "Sampling phase scan"),
    ("h 和 LPF 联合优化", "Joint h and LPF optimization"),
    ("8-ary GFSK", "8-ary GFSK"),
    ("8-branch", "8-branch"),
    ("8 状态", "8 states"),
    ("64 状态", "64 states"),
    ("4 状态", "4 states"),
    ("1符号记忆", "1-symbol memory"),
    ("2符号记忆", "2-symbol memory"),
    ("3符号记忆", "3-symbol memory"),
    ("连续相位", "Continuous-phase"),
    ("码间干扰", "Inter-symbol interference (ISI)"),
    ("相干检测", "Coherent detection"),
    ("相干解调", "Coherent demodulation"),
    ("频率跳变", "Frequency jump"),
    ("相位积分", "Phase integration"),
    ("上采样", "Upsampling"),
    ("混频", "Mixing"),
    ("滤波", "Filtering"),
    ("取模", "Magnitude"),
    ("归一化", "Normalization"),
    ("延迟补偿", "Delay compensation"),
    ("群延迟", "Group delay"),
    ("带外抑制", "Out-of-band rejection"),
    ("通带截止", "Passband cutoff"),
    ("阻带截止", "Stopband cutoff"),
    ("通带带宽", "Passband bandwidth"),
    ("过渡带", "Transition band"),
    ("旁瓣抑制", "Sidelobe suppression"),
    ("脉冲响应", "Impulse response"),
    ("频率响应", "Frequency response"),
    ("幅度响应", "Magnitude response"),
    ("相位响应", "Phase response"),
    ("稳态", "Steady state"),
    ("边界效应", "Boundary effects"),
    ("防护带", "Guard band"),
    ("前导", "Preamble"),
    ("后导", "Postamble"),
    ("有效", "Valid"),
    ("随机", "Random"),
    ("固定", "Fixed"),
    ("相同", "Identical"),
    ("不同", "Different"),
    ("完全", "Fully"),
    ("部分", "Partially"),
    ("主要", "Main"),
    ("次要", "Secondary"),
    ("所有", "All"),
    ("每个", "Each"),
    ("任意", "Any"),
    ("其他", "Other"),
    ("例如", "For example"),
    ("比如", "For example"),
    ("注意", "Note"),
    ("警告", "Warning"),
    ("错误", "Error"),
    ("原因", "Reason"),
    ("修复", "Fix"),
    ("症状", "Symptom"),
    ("因此", "Therefore"),
    ("因为", "Because"),
    ("所以", "So"),
    ("但是", "But"),
    ("然而", "However"),
    ("如果", "If"),
    ("否则", "Otherwise"),
    ("当", "When"),
    ("对于", "For"),
    ("其中", "Where"),
    ("通过", "Through"),
    ("使用", "Using"),
    ("基于", "Based on"),
    ("由于", "Due to"),
    ("导致", "Causes"),
    ("产生", "Generates"),
    ("计算", "Calculate"),
    ("得到", "Obtain"),
    ("获得", "Get"),
    ("输出", "Output"),
    ("输入", "Input"),
    ("返回", "Return"),
    ("设置", "Set"),
    ("配置", "Configure"),
    ("选择", "Select"),
    ("确定", "Determine"),
    ("获取", "Acquire"),
    ("提取", "Extract"),
    ("查找", "Find"),
    ("搜索", "Search"),
    ("比较", "Compare"),
    ("匹配", "Match"),
    ("对应", "Correspond to"),
    ("转换", "Convert"),
    ("变换", "Transform"),
    ("更新", "Update"),
    ("重置", "Reset"),
    ("初始化", "Initialize"),
    ("开始", "Start"),
    ("结束", "End"),
    ("停止", "Stop"),
    ("暂停", "Pause"),
    ("继续", "Continue"),
    ("重复", "Repeat"),
    ("循环", "Loop"),
    ("迭代", "Iterate"),
    ("遍历", "Traverse"),
    ("调用", "Call"),
    ("执行", "Execute"),
    ("运行", "Run"),
    ("加载", "Load"),
    ("保存", "Save"),
    ("读取", "Read"),
    ("写入", "Write"),
    ("显示", "Display"),
    ("打印", "Print"),
    ("绘制", "Plot"),
    ("画图", "Plot"),
    ("标注", "Annotate"),
    ("注释", "Comment"),
    ("说明", "Description"),
    ("描述", "Description"),
    ("信息", "Information"),
    ("数据", "Data"),
    ("变量", "Variable"),
    ("常量", "Constant"),
    ("函数", "Function"),
    ("方法", "Method"),
    ("类", "Class"),
    ("对象", "Object"),
    ("结构", "Structure"),
    ("数组", "Array"),
    ("矩阵", "Matrix"),
    ("向量", "Vector"),
    ("标量", "Scalar"),
    ("元素", "Element"),
    ("分量", "Component"),
    ("维度", "Dimension"),
    ("大小", "Size"),
    ("长度", "Length"),
    ("宽度", "Width"),
    ("高度", "Height"),
    ("深度", "Depth"),
    ("范围", "Range"),
    ("区间", "Interval"),
    ("区域", "Region"),
    ("边界", "Boundary"),
    ("中心", "Center"),
    ("中间", "Middle"),
    ("内部", "Internal"),
    ("外部", "External"),
    ("左侧", "Left"),
    ("右侧", "Right"),
    ("上方", "Above"),
    ("下方", "Below"),
    ("前面", "Front"),
    ("后面", "Back"),
    ("顶部", "Top"),
    ("底部", "Bottom"),
    ("起点", "Start point"),
    ("终点", "End point"),
    ("原点", "Origin"),
    ("参考点", "Reference point"),
    ("基准点", "Benchmark point"),
    ("关键点", "Key point"),
    ("临界点", "Critical point"),
    ("转折点", "Turning point"),
    ("峰值点", "Peak point"),
    ("谷值点", "Valley point"),
    ("零点", "Zero point"),
    ("极点", "Pole"),
    ("奇点", "Singularity"),
    ("节点", "Node"),
    ("顶点", "Vertex"),
    ("交点", "Intersection"),
    ("切点", "Tangent point"),
    ("触点", "Contact point"),
    ("中点", "Midpoint"),
    ("重心", "Center of gravity"),
    ("质心", "Centroid"),
    ("焦点", "Focus"),
    ("中心点", "Center point"),
    ("图", "Figure"),
    ("架构：", "Architecture: "),
    ("发射：", "Tx: "),
    ("信道：", "Channel: "),
    ("ISI 感知设计：", "ISI-aware design: "),
    ("核心成果", "Core result"),
    ("历史实验", "Historical experiment"),
    ("最终归档", "Final archived version"),
    ("信道滤波器", "Channel filter"),
    ("信道滤波器：", "Channel filter: "),
    ("高斯频率脉冲（发射端）", "Gaussian frequency pulse (transmitter)"),
    ("高斯脉冲整形", "Gaussian pulse shaping"),
    ("高斯脉冲群延迟", "Gaussian pulse group delay"),
    ("Tone混频低通滤波器：", "Tone mixer lowpass filter: "),
    ("Tone混频低通滤波器", "Tone mixer lowpass filter"),
    ("Tone LPF 设计", "Tone LPF design"),
    ("滤波器设计", "Filter design"),
    ("滤波器设计与延迟计算", "Filter design and delay calculation"),
    ("低通FIR", "Lowpass FIR"),
    ("优化：", "Optimization: "),
    ("优化理由", "Optimization rationale"),
    ("窗函数：", "Window function: "),
    ("窗函数", "Window function"),
    ("截止频率：", "Cutoff frequency: "),
    ("截止频率", "Cutoff frequency"),
    ("延迟：", "Delay: "),
    ("阶数：", "Order: "),
    ("总延迟", "Total delay"),
    ("采样时刻：", "Sampling instant: "),
    ("采样时刻", "Sampling instant"),
    ("采样索引：", "Sampling index: "),
    ("采样索引", "Sampling index"),
    ("采样点：", "Sampling point: "),
    ("采样点", "Sampling point"),
    ("采样索引越界", "Sampling index out of bounds"),
    ("Gray 编解码映射", "Gray encoding/decoding mapping"),
    ("Gray 编码", "Gray encoding"),
    ("Gray 映射", "Gray mapping"),
    ("频率编号", "Frequency index"),
    ("符号率", "Symbol rate"),
    ("采样率", "Sampling rate"),
    ("每符号采样", "Samples per symbol"),
    ("非线性", "Nonlinear"),
    ("分布", "distribution"),
    ("有效符号", "Valid symbol"),
    ("调制指数", "Modulation index"),
    ("相邻tone", "Adjacent tone"),
    ("间隔", "spacing"),
    ("高斯滤波", "Gaussian filter"),
    ("符号", "Symbol"),
    ("采样数", "sample count"),
    ("进制", "-ary"),
    ("发送", "Transmit"),
    ("接收", "Receive"),
    ("前端", "frontend"),
    ("后端", "backend"),
    ("参数", "Parameters"),
    ("可配置", "Configurable"),
    ("判决", "Decision"),
    ("深度", "Depth"),
    ("滤波器", "Filter"),
    ("设计", "Design"),
    ("计算", "Calculation"),
    ("低通", "Lowpass"),
    ("优化", "Optimization"),
    ("理由", "Rationale"),
    ("窗", "Window"),
    ("截止", "Cutoff"),
    ("频率", "Frequency"),
    ("总", "Total"),
    ("时刻", "Instant"),
    ("索引", "Index"),
    ("点", "Point"),
    ("越界", "Out of bounds"),
    ("编解码", "Encoding/decoding"),
    ("映射", "Mapping"),
    ("编号", "Index"),
    ("辅助", "Helper"),
    ("生成", "Generate"),
    ("预", "Pre-"),
    ("验证", "Verify"),
    ("模板", "Template"),
    ("解码器", "Decoder"),
    ("序列", "Sequence"),
    ("检测", "Detection"),
    ("硬", "Hard"),
    ("软", "Soft"),
    ("度量", "Metric"),
    ("前向", "Forward"),
    ("递推", "Recursion"),
    ("状态", "State"),
    ("定义", "Definition"),
    ("数", "Number"),
    ("转移", "Transition"),
    ("路径", "Path"),
    ("幸存", "Survivor"),
    ("最优", "Optimal"),
    ("主", "Main"),
    ("扫描", "Sweep"),
    ("噪声", "Noise"),
    ("方差", "Variance"),
    ("功率", "Power"),
    ("校验", "Check"),
    ("卡洛", "Carlo"),
    ("仿真", "Simulation"),
    ("时间", "Time"),
    ("运行", "Run"),
    ("可调", "Adjustable"),
    ("使用", "Usage"),
    ("说明", "Instructions"),
    ("可视", "Visualization"),
    ("信号", "Signal"),
    ("频谱", "Spectrum"),
    ("星座", "Constellation"),
    ("图", "Diagram"),
    ("误码率", "Bit error rate"),
    ("曲线", "Curve"),
    ("错误", "Error"),
    ("位置", "Location"),
    ("对比", "Comparison"),
    ("分析", "Analysis"),
    ("统计", "Statistics"),
    ("测试", "Test"),
    ("优化", "Optimize"),
    ("评估", "Evaluate"),
    ("性能", "Performance"),
    ("指标", "Metric"),
    ("汇总", "Summary"),
    ("结论", "Conclusion"),
    ("验证", "Verification"),
    ("确认", "Confirm"),
    ("检查", "Check"),
    ("符号", "Symbol"),
    ("内部", "Internal"),
    ("分支", "Branch"),
    ("度量", "Metric"),
    ("每", "Per"),
    ("分支", "Branch"),
    ("最优", "Optimal"),
    ("相位", "Phase"),
    ("采样", "Sampling"),
    ("相位", "Phase"),
    ("扫描", "Scan"),
    ("联合", "Joint"),
    ("优化", "Optimization"),
    ("连续", "Continuous"),
    ("相位", "Phase"),
    ("码", "Code"),
    ("间", "Inter-"),
    ("干扰", "Interference"),
    ("相干", "Coherent"),
    ("检测", "Detection"),
    ("解调", "Demodulation"),
    ("频率", "Frequency"),
    ("跳变", "Jump"),
    ("相位", "Phase"),
    ("积分", "Integration"),
    ("上", "Up-"),
    ("采样", "Sampling"),
    ("混频", "Mixing"),
    ("滤波", "Filtering"),
    ("取模", "Magnitude"),
    ("归一化", "Normalization"),
    ("延迟", "Delay"),
    ("补偿", "Compensation"),
    ("群", "Group"),
    ("延迟", "Delay"),
    ("带", "Band"),
    ("外", "Out"),
    ("抑制", "Rejection"),
    ("通带", "Passband"),
    ("截止", "Cutoff"),
    ("阻带", "Stopband"),
    ("截止", "Cutoff"),
    ("通带", "Passband"),
    ("带宽", "Bandwidth"),
    ("过渡", "Transition"),
    ("带", "Band"),
    ("旁瓣", "Sidelobe"),
    ("抑制", "Suppression"),
    ("脉冲", "Pulse"),
    ("响应", "Response"),
    ("频率", "Frequency"),
    ("响应", "Response"),
    ("幅度", "Magnitude"),
    ("响应", "Response"),
    ("相位", "Phase"),
    ("响应", "Response"),
    ("稳态", "Steady"),
    ("状态", "State"),
    ("边界", "Boundary"),
    ("效应", "Effect"),
    ("防护", "Guard"),
    ("带", "Band"),
    ("前导", "Preamble"),
    ("后导", "Postamble"),
    ("有效", "Valid"),
    ("随机", "Random"),
    ("固定", "Fixed"),
    ("相同", "Identical"),
    ("不同", "Different"),
    ("完全", "Fully"),
    ("部分", "Partially"),
    ("主要", "Main"),
    ("次要", "Secondary"),
    ("所有", "All"),
    ("每个", "Each"),
    ("任意", "Any"),
    ("其他", "Other"),
    ("例如", "For example"),
    ("比如", "For example"),
    ("注意", "Note"),
    ("警告", "Warning"),
    ("错误", "Error"),
    ("原因", "Reason"),
    ("修复", "Fix"),
    ("症状", "Symptom"),
    ("因此", "Therefore"),
    ("因为", "Because"),
    ("所以", "So"),
    ("但是", "But"),
    ("然而", "However"),
    ("如果", "If"),
    ("否则", "Otherwise"),
    ("当", "When"),
    ("对于", "For"),
    ("其中", "Where"),
    ("通过", "Through"),
    ("使用", "Using"),
    ("基于", "Based on"),
    ("由于", "Due to"),
    ("导致", "Causes"),
    ("产生", "Generates"),
    ("计算", "Calculate"),
    ("得到", "Obtain"),
    ("获得", "Get"),
    ("输出", "Output"),
    ("输入", "Input"),
    ("返回", "Return"),
    ("设置", "Set"),
    ("配置", "Configure"),
    ("选择", "Select"),
    ("确定", "Determine"),
    ("获取", "Acquire"),
    ("提取", "Extract"),
    ("查找", "Find"),
    ("搜索", "Search"),
    ("比较", "Compare"),
    ("匹配", "Match"),
    ("对应", "Correspond to"),
    ("转换", "Convert"),
    ("变换", "Transform"),
    ("更新", "Update"),
    ("重置", "Reset"),
    ("初始化", "Initialize"),
    ("开始", "Start"),
    ("结束", "End"),
    ("停止", "Stop"),
    ("暂停", "Pause"),
    ("继续", "Continue"),
    ("重复", "Repeat"),
    ("循环", "Loop"),
    ("迭代", "Iterate"),
    ("遍历", "Traverse"),
    ("调用", "Call"),
    ("执行", "Execute"),
    ("运行", "Run"),
    ("加载", "Load"),
    ("保存", "Save"),
    ("读取", "Read"),
    ("写入", "Write"),
    ("显示", "Display"),
    ("打印", "Print"),
    ("绘制", "Plot"),
    ("画图", "Plot"),
    ("标注", "Annotate"),
    ("注释", "Comment"),
    ("说明", "Description"),
    ("描述", "Description"),
    ("信息", "Information"),
    ("数据", "Data"),
    ("变量", "Variable"),
    ("常量", "Constant"),
    ("函数", "Function"),
    ("方法", "Method"),
    ("类", "Class"),
    ("对象", "Object"),
    ("结构", "Structure"),
    ("数组", "Array"),
    ("矩阵", "Matrix"),
    ("向量", "Vector"),
    ("标量", "Scalar"),
    ("元素", "Element"),
    ("分量", "Component"),
    ("维度", "Dimension"),
    ("大小", "Size"),
    ("长度", "Length"),
    ("宽度", "Width"),
    ("高度", "Height"),
    ("深度", "Depth"),
    ("范围", "Range"),
    ("区间", "Interval"),
    ("区域", "Region"),
    ("边界", "Boundary"),
    ("中心", "Center"),
    ("中间", "Middle"),
    ("内部", "Internal"),
    ("外部", "External"),
    ("左侧", "Left"),
    ("右侧", "Right"),
    ("上方", "Above"),
    ("下方", "Below"),
    ("前面", "Front"),
    ("后面", "Back"),
    ("顶部", "Top"),
    ("底部", "Bottom"),
    ("起点", "Start point"),
    ("终点", "End point"),
    ("原点", "Origin"),
    ("参考点", "Reference point"),
    ("基准点", "Benchmark point"),
    ("关键点", "Key point"),
    ("临界点", "Critical point"),
    ("转折点", "Turning point"),
    ("峰值点", "Peak point"),
    ("谷值点", "Valley point"),
    ("零点", "Zero point"),
    ("极点", "Pole"),
    ("奇点", "Singularity"),
    ("节点", "Node"),
    ("顶点", "Vertex"),
    ("交点", "Intersection"),
    ("切点", "Tangent point"),
    ("触点", "Contact point"),
    ("中点", "Midpoint"),
    ("重心", "Center of gravity"),
    ("质心", "Centroid"),
    ("焦点", "Focus"),
    ("中心点", "Center point"),
    ("个", ""),
    ("型", "Type"),
    ("共", "Total"),
    ("例", "Example"),
    ("行", "Row"),
    ("绘", "Plot"),
    ("在", "At"),
    ("已", "Already"),
    ("值", "Value"),
    ("为", "As"),
    ("高", "High"),
    ("与", "With"),
    ("的", "of"),
    ("器", "Filter"),
    ("码", "Code"),
    ("从", "From"),
    ("新", "New"),
    ("是", "Is"),
    ("到", "To"),
    ("度", "Degree"),
    ("预", "Pre-"),
    ("列", "Column"),
    ("让", "Let"),
    ("对", "For"),
    ("和", "And"),
    ("轴", "Axis"),
    ("取", "Take"),
    ("推", "Push"),
    ("或", "Or"),
    ("只", "Only"),
    ("子", "Sub-"),
    ("不", "Not"),
]

def translate_file(filepath):
    with open(filepath, 'r', encoding='utf-8') as f:
        content = f.read()
    
    lines = content.split('\n')
    changed = 0
    
    for i, line in enumerate(lines):
        # Find the comment part (after %)
        pct_idx = line.find('%')
        if pct_idx == -1:
            continue
        
        code_part = line[:pct_idx]
        comment_part = line[pct_idx:]
        
        # Check if comment part contains Chinese
        if not re.search(r'[\u4e00-\u9fff]', comment_part):
            continue
        
        original_comment = comment_part
        for old, new in replacements:
            if old in comment_part:
                comment_part = comment_part.replace(old, new)
        
        if comment_part != original_comment:
            lines[i] = code_part + comment_part
            changed += 1
    
    new_content = '\n'.join(lines)
    if new_content != content:
        with open(filepath, 'w', encoding='utf-8') as f:
            f.write(new_content)
        return True, changed
    return False, 0

def main():
    ws_dir = r"C:\Users\Administrator\Documents\Kimi\Workspaces\mgfsk_viterbi"
    m_files = [f for f in sorted(os.listdir(ws_dir)) if f.endswith('.m')]
    
    total_changed = 0
    modified_files = []
    
    for fname in m_files:
        fpath = os.path.join(ws_dir, fname)
        modified, count = translate_file(fpath)
        if modified:
            modified_files.append(fname)
            total_changed += count
            print(f"Modified {fname}: {count} lines changed")
    
    print(f"\nTotal: {len(modified_files)} files modified, {total_changed} lines changed")
    return {"modified_files": modified_files, "total_changed": total_changed}

if __name__ == '__main__':
    main()
